version: "3.9"
services:
  db1:
    image: postgres
    container_name: db1
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=dishes
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  db2:
    image: postgres
    container_name: db2
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=postgres
      - POSTGRES_DB=orders
      - PGDATA=/var/lib/postgresql/data
    volumes:
      - ./db/shortcut/data:/var/lib/postgresql/data
    restart: always
  dishes:
    image: job4j_dish
    container_name: dish
    environment:
      - JDBC_URL=jdbc:postgresql://db1:5432/dishes
      - JDBC_USERNAME=postgres
      - JDBC_PASSWORD=pass
      - JDBC_DRIVER=org.postgresql.Driver
    depends_on:
      - db1
  job4j_order:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - JDBC_URL=jdbc:postgresql://db2:5432/orders
        - JDBC_USERNAME=postgres
        - JDBC_PASSWORD=pass
        - JDBC_DRIVER=org.postgresql.Driver
    container_name: job4j_tracker
    depends_on:
        - db2